### ISSUE TITLE
Better code

### ISSUE THREAD

**Issue by bacloud14** [bacloud14/Interactive_Arrays#1]
I just jumped to JavaScript manipulating Dom and Asyn programming. This is very new to me, I know code is very poorly written. There is only one JS file and one HTML file. All code is concerned.
Task: code review or pass into : https://jshint.com/

**Comment by hamczu** [comment]
just FYI: most of the JS community switched to ESLint

**Comment by bacloud14** [comment]
It seems to be the same, for a poorly written code, and yes, I agree.

**Comment by Marie-Burns22** [comment]
Hi, I am a newish developer and looking for my first open source contribution. I looked through the JS file and saw some things I think I can improve. Although I am not sure how to make all the improvements needed, there are some minor things I know how to cleanup.  Also, it seems that JS is moving away from using `var` and instead using `let` and `const`. Would changing that be something you are interested in for this project? I'd love to fork, clone, and make a branch to work on. I could do one for the minor things and a different branch for the var/let/const changes. Thanks!

**Comment by bacloud14** [comment]
Hello Marie, 
Oh of course ! I know some of these new Ecmascript 6 new features, but I am not fully aware.
Yes I am very interested, the solution itself is very easy to debug as you might see, just a single JS file with some dependencies, so debugging is easy and direct on the browser. Go for it !
Thanks Marie.

**Comment by Marie-Burns22** [comment]
Great! I will fork, clone, and make a new branch to work on over the next week.

**Comment by bacloud14** [comment]
Hi Marie
Any follow up ? I will also work on this issue the next weekend. 
Regards.

**Comment by Marie-Burns22** [comment]
Thank you for checking in! My apologies for letting this slip. I will move it up on my priorities this week and have some updates for you by the weekend. Thank you for your patience.

**Comment by bacloud14** [comment]
Great, thank you so much!

**Comment by Marie-Burns22** [comment]
Hi, I looked through the code more today and the only parts I can solidly make any recommendation about is in regard to the use of var.  The rest I am not comfortable making any suggestions so my apologies for not being more helpful. 

I also am not sure about backwards compatibility and compiling issues, but for ES6 they stopped used `var` and now use `const` and `let`. You use `const` when the value will not change. However, you can assign an object or array to a `const` and change the elements inside of it. You use `let` when the value will change. For example, in the for loops, you would `let i = 0` since `i` will be incremented. 

Also, you can move the declaration of the variable i into the for loop.  For example: `for(let i = 0; i < array.length; i ++)`

I hope the minor suggestion works and helps.

**Comment by bacloud14** [comment]
Very interesting Marie, I will see, I will work on that today.
Many thanks.
